import LoadingButton from '@mui/lab/LoadingButton'
import Box from '@mui/material/Box'
import InputAdornment from '@mui/material/InputAdornment'
import Paper from '@mui/material/Paper'
import Table from '@mui/material/Table'
import TableBody from '@mui/material/TableBody'
import TableCell from '@mui/material/TableCell'
import TableContainer from '@mui/material/TableContainer'
import TableRow from '@mui/material/TableRow'
import TextField from '@mui/material/TextField'
import { useForm } from 'react-hook-form'

import { Form, Submit } from '@redwoodjs/forms'

import CharQtyInput from 'src/components/CharQtyInput/CharQtyInput'
import charNames from 'src/lib/charNames'

const FontForm = (props) => {
  const onSubmit = (data) => {
    const formattedData = { name: data.name }
    const size = parseInt(data.size)
    if (!isNaN(size)) {
      formattedData.size = size
    }
    const chars = {}
    for (const [field, val] of Object.entries(data)) {
      if (field.startsWith('char-') && !isNaN(val)) {
        chars[field] = val
      }
    }
    formattedData.chars = JSON.stringify(chars)
    props.onSave(formattedData, props?.font?.id)
  }

  const formMethods = useForm({ mode: 'onBlur' })
  const { register } = formMethods

  const chars = props.font ? JSON.parse(props.font.chars) : null

  return (
    <Form
      autoComplete="off"
      onSubmit={onSubmit}
      error={props.error}
      sx={{
        '& .MuiTextField-root': { m: 1, width: '25ch' },
      }}
      formMethods={formMethods}
    >
      <TextField
        {...register('name', { required: true })}
        required
        label="Name"
        defaultValue={props.font?.name}
        placeholder="Comic Sans"
      />

      <TextField
        {...register('size')}
        label="Size"
        defaultValue={props.font?.size}
        InputProps={{
          endAdornment: <InputAdornment position="end">pt.</InputAdornment>,
        }}
      />

      <TableContainer component={Paper}>
        <Table sx={{ minWidth: 650 }}>
          <TableBody>
            <TableRow>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-ffi'}
                chars={chars}
              >
                {charNames['char-lowercase-ffi']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-fl'}
                chars={chars}
              >
                {charNames['char-lowercase-fl']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-fiveEm'}
                chars={chars}
              >
                {charNames['char-fiveEm']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-fourEm'}
                chars={chars}
              >
                {charNames['char-fourEm']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-apostrophe'}
                chars={chars}
              >
                {charNames['char-apostrophe']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-k'}
                chars={chars}
              >
                {charNames['char-lowercase-k']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-e'}
                chars={chars}
                rowSpan={4}
                colSpan={2}
              >
                {charNames['char-lowercase-e']}
              </CharQtyInput>
              <TableCell sx={{ border: 1 }} rowSpan={9}></TableCell>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-one'}
                chars={chars}
              >
                {charNames['char-one']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-two'}
                chars={chars}
              >
                {charNames['char-two']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-three'}
                chars={chars}
              >
                {charNames['char-three']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-four'}
                chars={chars}
              >
                {charNames['char-four']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-five'}
                chars={chars}
              >
                {charNames['char-five']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-six'}
                chars={chars}
              >
                {charNames['char-six']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-seven'}
                chars={chars}
              >
                {charNames['char-seven']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-eight'}
                chars={chars}
              >
                {charNames['char-eight']}
              </CharQtyInput>
              <TableCell sx={{ border: 1 }} rowSpan={9}></TableCell>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-usd'}
                chars={chars}
              >
                {charNames['char-usd']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-gbp'}
                chars={chars}
              >
                {charNames['char-gbp']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-dash'}
                chars={chars}
              >
                {charNames['char-dash']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-AE'}
                chars={chars}
              >
                {charNames['char-uppercase-AE']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-OE'}
                chars={chars}
              >
                {charNames['char-uppercase-OE']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-ae'}
                chars={chars}
              >
                {charNames['char-lowercase-ae']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-oe'}
                chars={chars}
              >
                {charNames['char-lowercase-oe']}
              </CharQtyInput>
            </TableRow>
            <TableRow>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-j'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-j']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-b'}
                chars={chars}
                rowSpan={3}
              >
                {charNames['char-lowercase-b']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-c'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-c']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-d'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-d']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-i'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-i']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-s'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-s']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-f'}
                chars={chars}
                rowSpan={3}
              >
                {charNames['char-lowercase-f']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-g'}
                chars={chars}
                rowSpan={3}
              >
                {charNames['char-lowercase-g']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-ff'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-ff']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-nine'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-nine']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-A'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-A']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-B'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-B']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-C'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-C']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-D'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-D']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-E'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-E']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-F'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-F']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-G'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-G']}
              </CharQtyInput>
            </TableRow>
            <TableRow></TableRow>
            <TableRow>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-question'}
                chars={chars}
              >
                {charNames['char-question']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-fi'}
                chars={chars}
              >
                {charNames['char-lowercase-fi']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-zero'}
                chars={chars}
              >
                {charNames['char-zero']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-H'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-H']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-I'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-I']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-K'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-K']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-L'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-L']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-M'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-M']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-N'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-N']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-O'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-O']}
              </CharQtyInput>
            </TableRow>
            <TableRow>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-exclamation'}
                chars={chars}
              >
                {charNames['char-exclamation']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-l'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-l']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-m'}
                chars={chars}
                rowSpan={2}
                colSpan={2}
              >
                {charNames['char-lowercase-m']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-n'}
                chars={chars}
                rowSpan={2}
                colSpan={2}
              >
                {charNames['char-lowercase-n']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-h'}
                chars={chars}
                rowSpan={2}
                colSpan={2}
              >
                {charNames['char-lowercase-h']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-o'}
                chars={chars}
                rowSpan={2}
                colSpan={2}
              >
                {charNames['char-lowercase-o']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-y'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-y']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-p'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-p']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-w'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-w']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-comma'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-comma']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-enQuad'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-enQuad']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-emQuad'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-emQuad']}
              </CharQtyInput>
            </TableRow>
            <TableRow>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-z'}
                chars={chars}
              >
                {charNames['char-lowercase-z']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-P'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-P']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-Q'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-Q']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-R'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-R']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-S'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-S']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-T'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-T']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-V'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-V']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-W'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-W']}
              </CharQtyInput>
            </TableRow>
            <TableRow>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-x'}
                chars={chars}
              >
                {charNames['char-lowercase-x']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-v'}
                chars={chars}
                rowSpan={3}
              >
                {charNames['char-lowercase-v']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-u'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-u']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-t'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-t']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-threeEmSpace'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-threeEmSpace']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-a'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-a']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-r'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-lowercase-r']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-semicolon'}
                chars={chars}
              >
                {charNames['char-semicolon']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-colon'}
                chars={chars}
              >
                {charNames['char-colon']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-twoAndThreeEmQuad'}
                chars={chars}
                rowSpan={3}
                colSpan={2}
              >
                {charNames['char-twoAndThreeEmQuad']}
              </CharQtyInput>
            </TableRow>
            <TableRow>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-q'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-q']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-period'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-period']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-minus'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-minus']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-X'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-X']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-Y'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-Y']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-Z'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-Z']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-J'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-J']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-uppercase-U'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-uppercase-U']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-ampersand'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-ampersand']}
              </CharQtyInput>
              <CharQtyInput
                formMethods={formMethods}
                name={'char-lowercase-ffl'}
                chars={chars}
                rowSpan={2}
              >
                {charNames['char-lowercase-ffl']}
              </CharQtyInput>
            </TableRow>
          </TableBody>
        </Table>
      </TableContainer>

      <Box sx={{ '& > button': { m: 1 } }}>
        <LoadingButton
          component={Submit}
          loading={props.loading}
          variant="contained"
        >
          <span>save</span>
        </LoadingButton>
      </Box>
    </Form>
  )
}

export default FontForm
